# Travis CI integration

language: cpp

notifications:
  email: false

os: linux
dist: xenial
env:
  - BUILD_TYPE=Debug CPP11=ON
  - BUILD_TYPE=Debug CPP11=OFF
  - BUILD_TYPE=Release CPP11=ON
  - BUILD_TYPE=Release CPP11=OFF
compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DRAPIDSCHEMA_CPP_11=${CPP11} -DRAPIDSCHEMA_WITH_SCHEMA_GENERATION=ON ..

script:
  - make -j4 && make test