# Travis CI integration

language: cpp

notifications:
  email: false

os: linux
dist: xenial

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5  # test support for xtensa compiler works, which is a gcc5 derivative
            - doxygen
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5" BUILD_TYPE=Debug CPP11=ON SCHEMA_GENERATION=ON
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - doxygen
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5" BUILD_TYPE=Debug CPP11=ON SCHEMA_GENERATION=OFF
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - doxygen
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" BUILD_TYPE=Debug CPP11=OFF SCHEMA_GENERATION=ON
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test llvm-toolchain-precise-3.5
          packages:
            - g++-5 clang-3.5
            - doxygen
      env:
        - MATRIX_EVAL="CC=clang-3.5 && CXX=clang++-3.5" BUILD_TYPE=Debug CPP11=ON SCHEMA_GENERATION=ON
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 clang-5.0	
            - doxygen
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0" BUILD_TYPE=Debug CPP11=OFF SCHEMA_GENERATION=ON

before_install:
  - sudo apt-get update
  - sudo apt-get install -y graphviz mscgen dia 
  - eval "${MATRIX_EVAL}" && ${CC} --version && ${CXX} --version

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DRAPIDSCHEMA_CPP_11=${CPP11} -DRAPIDSCHEMA_WITH_SCHEMA_GENERATION=${SCHEMA_GENERATION} ..

script:
  - make -j4 && ./unittests/rapidschema_unittest && make test
  - make rapidschema_doxygen
