// Copyright (C) 2019 Christian Ledergerber

#ifndef INCLUDE_RAPIDSCHEMA_CONCEPTS_REQUIRES_MACRO_H_
#define INCLUDE_RAPIDSCHEMA_CONCEPTS_REQUIRES_MACRO_H_

#ifdef RAPIDSCHEMA_WITH_CONCEPTS
#define RAPIDSCHEMA_REQUIRES(x) requires x
#else
#define RAPIDSCHEMA_REQUIRES(x)
#endif

#endif  // INCLUDE_RAPIDSCHEMA_CONCEPTS_REQUIRES_MACRO_H_
